### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by otakuto** [stz2012/libarib25#11]
このソフトウェアのライセンスは独自のものですが一般的なライセンスへの変更予定などはないでしょうか?

**Comment by eternalharvest** [comment]
私も、ライセンスの問題点については以前から気になってはいました。
オリジナルの作者の茂木氏は安価な受信機の開発の一助になればという目的のもと、
現状有姿でユーザーの利用により生じた責任を一切持たないとの条件のもと、
公開されていたと思います。

ですから、個人的な解釈では茂木氏に特別コンタクトを取らなくても、
MIT License や Apache License のような
比較的ゆるいライセンスへの変更をしても問題はないかと思います。
礼儀的にライセンスの変更をした旨を通知した方が良いとは思いますが。

私自身の以前に出して取り込まれたプルリクの部分については、
いろいろな OS 向けにポーティングしたりビルドシステムに関するパッチで、
機能に対する付加的な機能は皆無ですし茂木氏と同じような意見なので、
茂木氏の提示した条件に合致する（開発者に、
特許上の問題や使用による責任を含めて何ら責任が及ばない形）
のライセンスであれば何ら権利を主張するつもりはありません。

その他、@stz2012 氏を始め他の開発者の同意は取り付ける必要はあるかと思います。
問題は、2ch 等から取り込まれたパッチですが、
おそらく今更権利を主張する人が現れるとは思いにくいですし、
権利の帰属を証明することが困難なので考えなくても良いのかなとは思います。

@otakuto 氏の想定する使用用途等を教えていただければ、
他の方もコメントしやすいのではないでしょうか？

**Comment by stz2012** [comment]
いろいろとご意見・ご提案、ありがとうございます。
以前、eternalharvest氏より、ライセンスの件、ご提案頂いていて、
Apache License 2で行こうかなと思っていた頃に、仕事が忙しくなりまして今に至ります。
せっかくなので、こちらで広く意見を聞いた上で決めたいと思っております。

**Comment by otakuto** [comment]
Gentooディストリビューションでのサポート, メンテナンスを行おうとしています.
私の用途ではApache License 2で問題ありません.

**Comment by eternalharvest** [comment]
> Gentooディストリビューションでのサポート, メンテナンスを行おうとしています.

すごいですね。
ディストリの公式でサポートされる感じでしょうか？

> 私の用途ではApache License 2で問題ありません.

私も、Apache License 2 に賛成です。

他のライセンスとの親和性も高く、かつモダンなライセンスみたいですし、
第三者が保有する特許を含むパッチを送ってきた場合のような
サブマリン特許問題にも対応できそうです。

また、具体的に「コントリビューション」や「コントリビュータ」という言葉の定義が明確になされており、
各コントリビューターの責任が限定されることが明示されている点は良いと思います。

Github の [コントリビュータ](https://github.com/stz2012/libarib25/graphs/contributors) ページによれば、他の開発者は @ero 氏のみのようですね。
すでに、氏の書いた Makefile のパッチは私のプルリクで置き換えられているようなので、
現在の成果物には含まれないのかもしれませんが貢献者として意見をもらえると嬉しいですね。
ということで、一応メンション飛ばしておきます。

もし、Apache License 2.0 で進めるということであれば、
ero 氏や 2ch の無名の貢献者のことについて、Apache License 2.0 が規定している、
NOTICE ファイルに書くという対応でも良いかと思います。
もちろん、最大の貢献者である茂木氏への謝辞も忘れずに。

**Comment by eternalharvest** [comment]
@stz2012 プルリクのマージ、ライセンスの変更ありがとうございます！
お手間をおかけしましたm(_ _)m

すでに libarib25 は完成の域に達していると思うので開発が活発になるとはあまり思えませんが、
利用者が増えてバグなどの情報が自然に集まって共有されるようになると良いですね！
また、ライセンスが明確になったことで利用者や利用用途の幅が広がれば嬉しいです。

**Comment by eru** [comment]
@eternalharvest すいません、気づくの遅くなりました。
既に変更後ですが、改めて賛成ということでコメントを残しておきます。

**Comment by eternalharvest** [comment]
いえ、私が ID の記載を間違っていたので
メンションを飛ばしたつもりが飛んでいなかったみたいです。
ご賛同ありがとうございます！
