### ISSUE TITLE
cmakeでのldconfigの実行について

### ISSUE THREAD

**Issue by otakuto** [stz2012/libarib25#17]
度重なるissue申し訳ありません
どうしてもcmake内でのldconfigの実行が必要でしょうか?
もしそうならoptionでldconfigの実行を選択できるようにしていただけないでしょうか?
必要でない場合cmakeでのldconfigを削除し, build.sh, build.batを経由してビルドするようにしていただけないでしょうか?
ldconfigはユーザーが叩くかshで呼ぶものだと考えていましたが, マルチプラットフォームやライトユーザー向けの配慮, 歴史的経緯があるなど, 理由がある場合は教えていただけると幸いです.

**Comment by eternalharvest** [comment]
@otakuto 

ldconfig 実行すると共有ライブラリの設定（依存関係情報）が書き換えられますし、ldconfig の実行には root 権限を要するのでユーザーの意図に反する可能性がありあまり良くないことなのかもしれませんね。

ただ、これは `make install` した際にのみ実行されるのであまり大きな問題にはならず、単に便利かなと思ってそのようにしていました。autoconf 等の環境でも `make install` のターゲット実行時に ldconfig を実行するようにしている記述をしているプロジェクトを見たことがあったので自然なことだと思っていましたが、確かによく考えて見るとあまり良いことではないように思うようになりました。

### ldconfig の自動実行無効化について
MacOS X 等 ldconfig コマンドを持たない環境ではそもそも実行がされないようになっていますが、以前の PR で Linux においても ldconfig の実行を無効化できるようにしています。詳細は、下記 PR を参照してください。

PR https://github.com/stz2012/libarib25/pull/8

### 歴史的経緯について
歴史的な経緯でいえば、もともと @stz2012  氏が Windows 版から Linux へ移植した際に Makefile によるビルドに移行していますが、その際にかかれた Makefile の `install` ターゲットには自動で ldconfig が実行されるように書かれていました。

その後、Windows と Linux で同じビルドシステム・単一コードベースでビルドできるよう cmake に移行したのですが、その過程で ldconfig の自動実行は省かれました。ただ、ビルド方法等を解説しているブログサイト等で ldconfig を手動で実行しないといけないことを指摘されているのを目にしましたため、もともとの挙動と同じように ldconfig を自動実行するように修正しました。

しかし、AlpineLinux 等のディストリや、MacOS X への移植等の過程で ldconfig コマンドがなかったり失敗する環境への対応が必要になり、現在はオプションで無効化可能な形になっています。

具体的にドキュメント化はされていませんが、現在の libarib25 にはリンクするべき PCSC ライブラリの指定（PCSC互換ライブラリの指定）や、ldconfig の自動実行等も含めて CMakeLists.txt を書き換えたりパッチを当てなくても cmake コマンドのオプションを指定するだけでかなり柔軟な構成が可能になっています。それぞれの、ビルドオプションについての詳しい説明は各 PR にそれぞれ詳細な説明がありますのでそちらを参照していただければと思います。

**Comment by otakuto** [comment]
ありがとうございます.
LDCONFIG_EXECUTABLEでできました.
すいませんもう少し良く調べるべきでした.
