### ISSUE TITLE
進行状況のパーセント表示について

### ISSUE THREAD

**Issue by noriy** [stz2012/libarib25#24]
サイズが2GBを超えるファイルの変換時、進行状況のパーセント表示が正しくない件について、
td.cの282行目の
        m = (int)(10000*offset/total);
を、
        m = (int)((uint64_t)10000*offset/total);
と修正すれば直るようです。
Linuxで確認しました。

**Comment by eternalharvest** [comment]
確かに、オリジナルのコードだと計算結果がオーバーフローしてしまいますね。
修正したとしても、ファイルサイズが 2^64 / 10000 バイトより大きい場合に表示がおかしくなってしまうので、浮動小数点で計算して int に丸めた方がいいのかなと一瞬思ったけど、そんな巨大なファイルをもっている人いないよね・・・

パッチ書いてプルリク送ると良いと思います！

**Comment by noriy** [comment]
はい、いまプルリク出しました。
